### ISSUE TITLE
Triplicated content-type headers

### ISSUE THREAD

**Issue by Grohden** [TarekkMA/gql_dio_link#4]
Hello, I'm using this to be able to use gql for web apps, but I've been having problems due to duplicated json headers being added by this package.

I'm having this:
```
headers:
 content-type: application/json application/json
 Content-type: application/json
```

First one is from this line
https://github.com/TarekkMA/gql_dio_link/blob/cf3debe72f1c8de922b7f112964a7384d486fba4/lib/src/dio_link.dart#L139

Second one is from this line
https://github.com/TarekkMA/gql_dio_link/blob/cf3debe72f1c8de922b7f112964a7384d486fba4/lib/src/dio_link.dart#L88

And the third is added by dio itself
https://github.com/flutterchina/dio/blob/9a46ea7c2a17d5adc99cc70abb5ffbf1d4aee757/dio/lib/src/dio.dart#L946

I'm gonna fork this package and fix it for me. I'm gonna need to make further tests on the native side, but I'm pretty sure this is related to new dio versions.. if you wish, I can open a PR for that :D

Btw, removing all refs to json from this package fixes the triplicated header problem

Edit: Heres some info versions
```yaml
  graphql: ^4.0.0-beta.3
  graphql_flutter: ^4.0.0-beta.3
  dio: ^3.0.10
  gql_dio_link: ^0.0.4
```

**Comment by TarekkMA** [comment]
Thank you a lot for opening an issue. 

If you are going to fix this please do in this repo https://github.com/gql-dart/gql because gql_dio_link is now a part of the gql family.

**Comment by TarekkMA** [comment]
In http they get around that by making headers keys case insensitive.
 
https://github.com/dart-lang/http/blob/master/lib/src/base_request.dart#L89

**Comment by Grohden** [comment]
@TarekkMA I find it weird that dio adds the header by itself... and worse, the header gets appended!

**Comment by TarekkMA** [comment]
> @TarekkMA I find it weird that dio adds the header by itself... and worse, the header gets appended!

I couldn't replicate the issue where the header gets appended. I can only see the issue with the duplicate headers.

This is the code I used to test this, I guess it's similar to what the link does.
```dart
main() async {
  var dio = Dio();
  dio.interceptors.add(LogInterceptor(
    responseBody: false,
    responseHeader: false,
    requestBody: true,
  ));
  Response response = await dio.post<dynamic>(
    'https://example.com',
    data: <String, dynamic>{
      "test": 44,
    },
    options: Options(
      responseType: ResponseType.json,
      contentType: "application/json",
      headers: {
        "Content-type": "application/json",
      },
    ),
  );
}
```
And these are the logs I get.
```
*** Request ***
uri: https://example.com
method: POST
responseType: ResponseType.json
followRedirects: true
connectTimeout: 0
receiveTimeout: 0
extra: {}
headers:
 content-type: application/json
 Content-type: application/json
data:
{test: 44}

*** Response ***
uri: https://example.com
```

Can share with me a version of the code that will cause this to happen?
